baseurl: "https://curiouscoding.nl"
title: CuriousCoding
theme: hugo-coder
languagecode: en
defaultcontentlanguage: en
pagination:
  pagerSize: 1000
pygmentsstyle: emacs
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
refLinksErrorLevel: "warning"

# Theme parameters
params:
  author: Ragnar {Groot Koerkamp}
  info: PhD High Throughput Bioinformatics @ BMI ETH Zurich
  description:
  publicBaseUrl: "https://curiouscoding.nl"
  keywords: >-
    blog,developer,phd,computational
    biology,dna,sequencing,personal,eth,eth zurich,
    pairwise alignment,DP,A*,minimizers,perfect hashing
  #avatarurl: /images/bike.jpg
  favicon_32: /images/bike-32.png
  favicon_16: /images/bike-64.png
  touchicon: /images/bike-64.png
  footercontent: >-
    This blog is <a href="https://github.com/RagnarGrootKoerkamp/research">open
    source</a> and licensed under <a
    href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>.
  hideFooter: false
  hideCredits: false
  hideCopyright: false
  since: 2021
  enableTwemoji: false
  colorScheme: light
  hidecolorschemetoggle: true
  math: true
  katex: false
  dateFormat: January 2006

  customSCSS: ["css/style.scss", "css/syntax.css"]
  # Saved as css/*.min.css
  fixedSCSS: ["css/slide.scss", "css/vs.css", "css/p99.css"]
  customJS: ["js/toc.js", "js/footnote.js", "js/code.js"]
  # Saved js/*.min.js
  fixedJS:
    [
      "js/alg-viz.js",
      "js/pkg/alg_viz.js",
      "js/pkg/alg_viz_bg.wasm",
      "js/pkg/package.json",
    ]
  customHtml:

  googleTagManager:
    id: G-VC3594H2Q8

  utterances:
    repo: ragnargrootkoerkamp/research
    issueTerm: pathname
    label: comments
    theme: github-dark

  social:
    - name: Github
      icon: fa fa-github fa-2x
      weight: 3
      url: "https://github.com/RagnarGrootKoerkamp/research/"
    - name: Twitter
      icon: fa fa-twitter fa-2x
      weight: 4
      url: "https://twitter.com/curious_coding/"
    - name: Bluesky
      icon: fa-brands fa-bluesky fa-2x
      weight: 4
      url: "https://bsky.app/profile/curiouscoding.nl"
    # - name: Mastodon
    #   icon: fa fa-mastodon fa-2x
    #   weight: 5
    #   url: "https://genomic.social/@curious_coding"
    #   rel: me
    - name: Google Scholar
      icon: fa google-scholar fa-2x
      weight: 6
      url: https://scholar.google.ch/citations?hl=en&user=yM9CokEAAAAJ
    - name: bioRxiv
      weight: 7
      url: https://www.biorxiv.org/search/author1%3ARagnar%2BGroot%2BKoerkamp
    - name: arXiv
      weight: 8
      url: https://arxiv.org/search/?query=Ragnar+Groot+Koerkamp&searchtype=author
    - name: Orcid
      icon: fa-brands fa-orcid fa-2x
      weight: 9
      url: https://orcid.org/0000-0002-2091-1237
    - name: Rss
      icon: fa fa-rss fa-2x
      weight: 10
      url: posts/index.xml
      rel: alternate
      type: application/rss+xml

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    lineNos: true
    # Use css classes with custom syntax file, instead of inlining colours.
    noClasses: false
    style: vs

taxonomies:
  category: categories
  tag: tags
  author: authors

menu:
  main:
    - name: All Posts
      url: /posts/
      weight: 1
    - name: WIP
      url: /wip
      weight: 2
    - name: Software
      url: /software/
      weight: 3
    - name: Projects
      url: /projects
      weight: 4
    - name: Talks
      url: /talks
      weight: 5
    - name: Publications
      url: /publications
      weight: 6
    - name: CV
      url: /cv
      weight: 7
    - name: About
      url: /about
      weight: 8
