#! release.toml
pre-release-commit-message = "v{{version}}"
shared-version = true
pre-release-replacements = [
  {file="CHANGELOG.md", search="## git", replace="## {{version}}", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## git", exactly=1},
  {file="pyproject.toml", search="version = .*", replace="version = \"{{version}}\""},
]
